version: '3.8'

volumes:
  dbdata:

networks:
  golang:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/home/rnd_user/project
    container_name: golang_migrate_api
    depends_on:
      - db
    networks:
      - golang

  db:
    build: ./docker/db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: golang_migrate_db
    hostname: golang_db
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql 
    networks:
      - golang